/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tvos_engine_njligames_com_android_JLIGameEngineTestLib */

#ifndef _Included_tvos_engine_njligames_com_android_JLIGameEngineTestLib
#define _Included_tvos_engine_njligames_com_android_JLIGameEngineTestLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tvos_engine_njligames_com_android_JLIGameEngineTestLib
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tvos_engine_njligames_com_android_JLIGameEngineTestLib_create
  (JNIEnv *, jclass)
{

}


/*
 * Class:     tvos_engine_njligames_com_android_JLIGameEngineTestLib
 * Method:    resize
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_tvos_engine_njligames_com_android_JLIGameEngineTestLib_resize
  (JNIEnv *, jclass, jint, jint, jint, jint)
{

}

/*
 * Class:     tvos_engine_njligames_com_android_JLIGameEngineTestLib
 * Method:    update
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_tvos_engine_njligames_com_android_JLIGameEngineTestLib_update
  (JNIEnv *, jclass, jfloat)
{

}

/*
 * Class:     tvos_engine_njligames_com_android_JLIGameEngineTestLib
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tvos_engine_njligames_com_android_JLIGameEngineTestLib_render
  (JNIEnv *, jclass)
{

}

/*
 * Class:     tvos_engine_njligames_com_android_JLIGameEngineTestLib
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tvos_engine_njligames_com_android_JLIGameEngineTestLib_destroy
  (JNIEnv *, jclass)
{

}

/*
 * Class:     tvos_engine_njligames_com_android_JLIGameEngineTestLib
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tvos_engine_njligames_com_android_JLIGameEngineTestLib_pause
  (JNIEnv *, jclass)
{

}

/*
 * Class:     tvos_engine_njligames_com_android_JLIGameEngineTestLib
 * Method:    unpause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tvos_engine_njligames_com_android_JLIGameEngineTestLib_unpause
  (JNIEnv *, jclass)
{

}

#ifdef __cplusplus
}
#endif
#endif
